package org.csc133.a2;
// java -cp out\artifacts\A2Prj\A2Prj.jar;JavaSE.jar com.codename1.impl.javase.Simulator org.csc133.a2.AppMain

import com.codename1.ui.plaf.UIManager;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class AppMain {

    public void init(Object context) {
        UIManager.initFirstTheme("/theme");
    }

    public void start() {
        new Game();
    }
}
